apiVersion: 1 # config file version

datasources:
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    isDefault: true
    uid: "P1EB995EACC6832D3"
    jsonData:
      azureAuthType: msi
    version: 1
