{
 "title": "Azure / Container Apps / Container App View",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ds",
    "label": "Datasource",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "sub",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "rg",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "containerapp",
    "label": "Container App",
    "query": {}
   },
   { "name": "ns", "label": "Namespace", "query": "microsoft.app/containerapps" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Allocated CPU (m cores)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$containerapp'\r\n| extend containers = todynamic(properties.template.containers)\r\n| mv-expand containers\r\n| summarize cpu = strcat(sum(todouble(containers.resources.cpu)) * 1000, \" m cores\")"
     },
     "subscription": "a5c27c0c-35f5-488f-9a2f-93e06c2eb56f",
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Max Allocated Memory (MB)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "dimensionFilters": [],
      "timeGrain": "auto"
     },
     "azureResourceGraph": {
      "query": "Resources\r\n| where subscriptionId =~ '$sub'\r\n| where resourceGroup =~ '$rg'\r\n| where type =~ '$ns'\r\n| where name =~ '$containerapp'\r\n| extend containers = todynamic(properties.template.containers)\r\n| mv-expand containers\r\n| summarize memory = strcat(\r\n      sum(\r\n        todouble(substring(containers.resources.memory, 0, strlen(containers.resources.memory) - 2)) \r\n        * 1000\r\n      ), \r\n    \" MB\")"
     },
     "subscription": "a5c27c0c-35f5-488f-9a2f-93e06c2eb56f",
     "subscriptions": [ "$sub" ]
    }
   ]
  },
  {
   "title": "Avg CPU Usage (m cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "UsageNanoCores",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Avg Memory Working Set Bytes (MB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "WorkingSetBytes",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Request Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Replica Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Max Replica Restart Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RestartCount",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Requests",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Replica Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Replicas",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Replica Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RestartCount",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Last Avg Network In Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RxBytes",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub",
     "subscriptions": [
      "a5c27c0c-35f5-488f-9a2f-93e06c2eb56f"
     ]
    }
   ]
  },
  {
   "title": "Avg Network In Bytes vs Network Out Bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 5, "y": 21 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "RxBytes",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TxBytes",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "Last Avg Network Out Bytes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "TxBytes",
      "metricNamespace": "$ns",
      "resourceGroup": "$rg",
      "resourceName": "$containerapp",
      "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
      "timeGrain": "auto"
     },
     "subscription": "$sub"
    }
   ]
  },
  {
   "title": "CPU (Split by Revision/Replica)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg CPU Usage by Revision (NanoCores)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "revisionName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "UsageNanoCores",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg CPU Usage by Replica (NanoCores)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "UsageNanoCores",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory (Split by Revision/Replica)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Memory Working Set Bytes by Revision (MB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "revisionName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "WorkingSetBytes",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg Memory Working Set Bytes by Replica (MB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "WorkingSetBytes",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto",
        "top": ""
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Network (Split by Revision/Replica)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Avg Network In Bytes by Revision",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "revisionName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "RxBytes",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg Network In Bytes by Replica",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "RxBytes",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg Network Out Bytes by Revision",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "revisionName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "TxBytes",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Avg Network Out Bytes by Replica",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 66 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Average",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "TxBytes",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  },
  {
   "title": "Requests (Split by Replica/Status Code)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests by Replica",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 77 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "podName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "Requests",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Requests by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 77 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "alias": "{{statuscode}}",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "statusCode",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "Requests",
        "metricNamespace": "$ns",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Replicas (Split by Revision)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replica Count by Revision",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "revisionName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "Replicas",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    },
    {
     "title": "Replica Restart Count by Revision",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 88 },
     "targets": [
      {
       "azureMonitor": {
        "aggregation": "Maximum",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimensionFilters": [
         {
          "dimension": "revisionName",
          "filters": [],
          "operator": "eq"
         }
        ],
        "metricName": "RestartCount",
        "metricNamespace": "$ns",
        "resourceGroup": "$rg",
        "resourceName": "$containerapp",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$containerapp",
        "timeGrain": "auto"
       },
       "subscription": "$sub"
      }
     ]
    }
   ]
  }
 ]
}